version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - VITE_API_URL=http://172.31.32.163:8000
    ports:
      - "5174:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DOMAIN=172.31.32.163
      - ENVIRONMENT=production
      - PROJECT_NAME="Full Stack FastAPI Project"
      - STACK_NAME=full-stack-fastapi-project
      - BACKEND_CORS_ORIGINS=http://172.31.32.163,http://172.31.32.163:5174
      - SECRET_KEY=changethis123
      - FIRST_SUPERUSER=devops@hng.tech
      - FIRST_SUPERUSER_PASSWORD=devops#HNG11
      - USERS_OPEN_REGISTRATION=True
      - SMTP_HOST=
      - SMTP_USER=
      - SMTP_PASSWORD=
      - EMAILS_FROM_EMAIL=info@example.com
      - SMTP_TLS=True
      - SMTP_SSL=False
      - SMTP_PORT=587
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=changethis123
    ports:
      - "8000:8000"  
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=changethis123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '8090:8090'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge